name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download Clojure CLI tools
      run: curl -O https://download.clojure.org/install/linux-install-1.10.1.697.sh
    - name: chmod +x Clojure CLI tools
      run: chmod +x linux-install-1.10.1.697.sh
    - name: Install Clojure CLI tools
      run: sudo ./linux-install-1.10.1.697.sh
    - name: Lint
      run: ./scripts/lint.sh
